(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const cfg=window.ANIMO_CONFIG||{};let sb=null,currentUser=null,signupMode=false,recoveryMode=false,data={temps:[],cleaning:[],actions:[],settings:null};
const configured=()=>cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes('VUL_HIER')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes('VUL_HIER');
const toast=t=>{let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),3500)};const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const formData=f=>Object.fromEntries(new FormData(f).entries());
function showView(name){$('#authView').hidden=name!=='auth';$('#recoveryView').hidden=name!=='recovery';$('#appView').hidden=name!=='app'}
function setAuthMode(signup){signupMode=signup;$('#tabLogin').classList.toggle('active',!signup);$('#tabSignup').classList.toggle('active',signup);$('#authSubmit').textContent=signup?'Account maken':'Inloggen';$('#forgotBtn').hidden=signup;$('#authMessage').textContent=''}
async function init(){if(!configured()){showView('auth');$('#authMessage').textContent='Vul eerst config.js correct in.';return}sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);sb.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){recoveryMode=true;currentUser=session?.user||null;showView('recovery');return}if(event==='SIGNED_OUT'){currentUser=null;recoveryMode=false;showView('auth');return}if(session?.user&&!recoveryMode)enterApp(session.user)});const {data:s}=await sb.auth.getSession();if(s.session&&!recoveryMode)await enterApp(s.session.user);else showView('auth')}
async function enterApp(user){currentUser=user;showView('app');$('#userEmail').textContent=user.email;$('#manageEmail').textContent=user.email;await loadAll()}
$('#tabLogin').onclick=()=>setAuthMode(false);$('#tabSignup').onclick=()=>setAuthMode(true);
$('#authForm').onsubmit=async e=>{e.preventDefault();let b=$('#authSubmit'),m=$('#authMessage');b.disabled=true;m.textContent='Even geduld...';try{let email=$('#email').value.trim(),password=$('#password').value;let result=signupMode?await sb.auth.signUp({email,password,options:{emailRedirectTo:location.href.split('#')[0].split('?')[0]}}):await sb.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(signupMode&&!result.data.session)m.textContent='Account gemaakt. Controleer je e-mail voor de bevestigingslink.';else m.textContent='Inloggen gelukt.'}catch(err){m.textContent=translateError(err.message)}finally{b.disabled=false}};
function translateError(x=''){if(x.includes('Invalid login credentials'))return'Ongeldig e-mailadres of wachtwoord.';if(x.includes('Email not confirmed'))return'Bevestig eerst je e-mailadres via de ontvangen mail.';if(x.includes('rate limit'))return'Te veel e-mails verstuurd. Wacht even of configureer eigen SMTP.';return x}
$('#forgotBtn').onclick=async()=>{let email=$('#email').value.trim();if(!email){$('#authMessage').textContent='Vul eerst je e-mailadres in.';return}let {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.href.split('#')[0].split('?')[0]});$('#authMessage').textContent=error?translateError(error.message):'Herstelmail verstuurd. Open de link in die e-mail.'};
$('#recoveryForm').onsubmit=async e=>{e.preventDefault();let a=$('#newPassword').value,b=$('#newPassword2').value,m=$('#recoveryMessage');if(a!==b){m.textContent='De wachtwoorden zijn niet gelijk.';return}let {error}=await sb.auth.updateUser({password:a});if(error){m.textContent=error.message;return}m.textContent='Wachtwoord gewijzigd. Je wordt doorgestuurd.';recoveryMode=false;history.replaceState({},'',location.pathname);setTimeout(()=>enterApp(currentUser),900)};
$('#logoutBtn').onclick=()=>sb.auth.signOut();$('#sendResetBtn').onclick=async()=>{let {error}=await sb.auth.resetPasswordForEmail(currentUser.email,{redirectTo:location.href.split('#')[0].split('?')[0]});toast(error?translateError(error.message):'Herstelmail verstuurd.')};
$$('#mainNav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));function go(id){$$('#mainNav button,.page').forEach(x=>x.classList.remove('active'));$(`#mainNav [data-page="${id}"]`)?.classList.add('active');$('#'+id).classList.add('active')}
$$('[data-modal]').forEach(b=>b.onclick=()=>$('#'+b.dataset.modal).showModal());$$('dialog form').forEach(f=>f.addEventListener('click',e=>{if(e.target.matches('[value=cancel]'))f.closest('dialog').close()}));
function defaults(){let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());document.querySelector('[name=recorded_at]').value=d.toISOString().slice(0,16);document.querySelector('[name=due_date]').value=d.toISOString().slice(0,10);$('#reportTo').value=d.toISOString().slice(0,10);let from=new Date();from.setDate(from.getDate()-30);$('#reportFrom').value=from.toISOString().slice(0,10)}defaults();
async function loadAll(){let [t,c,a,s]=await Promise.all([sb.from('temperature_records').select('*').order('recorded_at',{ascending:false}),sb.from('cleaning_tasks').select('*').order('created_at',{ascending:false}),sb.from('corrective_actions').select('*').order('created_at',{ascending:false}),sb.from('business_settings').select('*').maybeSingle()]);for(let r of [t,c,a,s])if(r.error){toast(r.error.message);return}data={temps:t.data||[],cleaning:c.data||[],actions:a.data||[],settings:s.data};render()}
async function insert(table,payload,dialog){let {error}=await sb.from(table).insert(payload);if(error)return toast(error.message);dialog.close();await loadAll();toast('Opgeslagen')}
$('#tempForm').onsubmit=async e=>{e.preventDefault();let o=formData(e.target);o.temperature=Number(o.temperature);await insert('temperature_records',o,$('#tempModal'));e.target.reset();defaults()};$('#cleanForm').onsubmit=async e=>{e.preventDefault();await insert('cleaning_tasks',formData(e.target),$('#cleanModal'));e.target.reset();defaults()};$('#actionForm').onsubmit=async e=>{e.preventDefault();await insert('corrective_actions',formData(e.target),$('#actionModal'));e.target.reset()};
window.animoDelete=async(table,id)=>{if(!confirm('Deze registratie verwijderen?'))return;let {error}=await sb.from(table).delete().eq('id',id);if(error)return toast(error.message);await loadAll()};window.animoToggle=async(table,id,done)=>{let {error}=await sb.from(table).update({done:!done}).eq('id',id);if(error)return toast(error.message);await loadAll()};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();let payload=formData(e.target),result=data.settings?await sb.from('business_settings').update(payload).eq('id',data.settings.id):await sb.from('business_settings').insert(payload);if(result.error)return toast(result.error.message);await loadAll();toast('Instellingen opgeslagen')};
$('#exportJson').onclick=()=>download('animo-backup.json',new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));function download(name,blob){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function render(){let today=new Date().toISOString().slice(0,10);$('#todayLabel').textContent=new Date().toLocaleDateString('nl-BE',{dateStyle:'long'});$('#statTemps').textContent=data.temps.filter(x=>x.recorded_at.slice(0,10)===today).length;$('#statCleaning').textContent=data.cleaning.filter(x=>!x.done).length;$('#statActions').textContent=data.actions.filter(x=>!x.done).length;$('#countTemps').textContent=data.temps.length;$('#countCleaning').textContent=data.cleaning.length;$('#countActions').textContent=data.actions.length;$('#tempEmpty').hidden=data.temps.length>0;$('#tempRows').innerHTML=data.temps.map(x=>`<tr><td>${esc(new Date(x.recorded_at).toLocaleString('nl-BE'))}</td><td>${esc(x.location)}</td><td>${esc(x.device)}</td><td>${esc(x.device_type)}</td><td>${esc(x.temperature)}</td><td>${esc(x.employee)}</td><td><button class="text-btn danger" onclick="animoDelete('temperature_records','${x.id}')">Verwijder</button></td></tr>`).join('');$('#cleanList').innerHTML=data.cleaning.map(x=>`<article class="item ${x.done?'done':''}"><div><h3>${esc(x.task)}</h3><p>${esc(x.location)} · ${esc(x.frequency)} · deadline ${esc(x.due_date)} · ${esc(x.owner)}</p></div><div class="item-actions"><button class="btn secondary" onclick="animoToggle('cleaning_tasks','${x.id}',${x.done})">${x.done?'Heropen':'Voltooid'}</button><button class="text-btn danger" onclick="animoDelete('cleaning_tasks','${x.id}')">Verwijder</button></div></article>`).join('')||'<div class="card empty">Nog geen kuistaken.</div>';$('#actionList').innerHTML=data.actions.map(x=>`<article class="item ${x.done?'done':''}"><div><h3>${esc(x.problem)}</h3><p>${esc(x.measure)} · ${esc(x.owner)}</p></div><div class="item-actions"><button class="btn secondary" onclick="animoToggle('corrective_actions','${x.id}',${x.done})">${x.done?'Heropen':'Afsluiten'}</button><button class="text-btn danger" onclick="animoDelete('corrective_actions','${x.id}')">Verwijder</button></div></article>`).join('')||'<div class="card empty">Nog geen correctieve acties.</div>';if(data.settings){for(let [k,v] of Object.entries(data.settings)){let el=$(`#settingsForm [name="${k}"]`);if(el)el.value=v||''}}}
$('#generatePdf').onclick=()=>{if(!window.jspdf)return toast('PDF-bibliotheek kon niet laden.');let from=$('#reportFrom').value,to=$('#reportTo').value,type=$('#reportType').value,{jsPDF}=window.jspdf,doc=new jsPDF(),company=data.settings?.company_name||'ANIMO HACCP',site=data.settings?.site_name||'';doc.setTextColor(13,45,82);doc.setFontSize(20);doc.text('ANIMO HACCP',14,18);doc.setFontSize(11);doc.setTextColor(60,70,80);doc.text(`${company}${site?' - '+site:''}`,14,26);doc.text(`Periode: ${from||'begin'} t/m ${to||'vandaag'}`,14,32);doc.text(`Aangemaakt: ${new Date().toLocaleString('nl-BE')}`,14,38);let y=46,within=d=>(!from||d.slice(0,10)>=from)&&(!to||d.slice(0,10)<=to);function table(title,head,body){doc.setTextColor(13,45,82);doc.setFontSize(14);doc.text(title,14,y);doc.autoTable({startY:y+4,head:[head],body:body.length?body:[['Geen registraties']],theme:'grid',headStyles:{fillColor:[13,45,82]},styles:{fontSize:8}});y=doc.lastAutoTable.finalY+12;if(y>260){doc.addPage();y=18}}if(type==='all'||type==='temperatures')table('Temperaturen',['Datum','Locatie','Toestel','Type','°C','Medewerker'],data.temps.filter(x=>within(x.recorded_at)).map(x=>[new Date(x.recorded_at).toLocaleString('nl-BE'),x.location,x.device,x.device_type,String(x.temperature),x.employee]));if(type==='all'||type==='cleaning')table('Kuisplan',['Taak','Locatie','Frequentie','Deadline','Verantwoordelijke','Status'],data.cleaning.filter(x=>within(x.due_date)).map(x=>[x.task,x.location,x.frequency,x.due_date,x.owner,x.done?'Voltooid':'Open']));if(type==='all'||type==='actions')table('Correctieve acties',['Probleem','Maatregel','Verantwoordelijke','Status','Datum'],data.actions.filter(x=>within(x.created_at)).map(x=>[x.problem,x.measure,x.owner,x.done?'Afgesloten':'Open',new Date(x.created_at).toLocaleDateString('nl-BE')]));doc.save(`ANIMO-HACCP-rapport-${from||today}-${to||today}.pdf`)};init()})();